#+SETUPFILE: /home/lowtroo/Number_Theory/stylish_white.theme
#+TITLE: Number Theory 1
#+AUTHOR: Lowtroo


* THE SERIES OF PRIMES
** Prime Numbers
A number p is said to be _prime_ if
1. p > 1
2. p has no positive divisors except 1 and p.

A number greater than 1 and not prime is called _composite_.
** Theorem 1:
Every positive integer, except 1, is a product of primes
*** Proof
Either $n$ is prime, when there is nothing to prove, or $n$ has divisors between 1 and n.
If $m$ is the least of these divisors, $m$ is prime; for otherwise
\[
\exists~l \ . \ 1 < l < m \ . \ l \mid m;
\]
and
\[
l \mid m \rightarrow l \mid n,
\]
which contradicts the definition of $m$.

Hence $n$ is prime or divisible by a prime less than $n$, say $p_{1}$, in which case
\[
n = p_{1}n_{1}, \quad 1 < n_{1} < n.
\]
Here either $n_{1}$ is prime, in which case the proof is completed,
or it is divisible by a prime $p_{2}$ less than $n_{1}$, in which case
\[
n = p_{1}n_{1} = p_{1}p_{2}n_{2}, \quad 1 < n_{2} < n_{1} < n.
\]
Repeating the argument, we obtain a sequence of decreasing numbers $n, n_{1}, \dots , n_{k-1}, \dots$,
all greater than $1$, for each of which the same alternative presents itself. Sooner or later we must accept
the first alternative, that $n_{k-1}$ is a prime, say $p_{k}$, and then
\[
n = p_{1}p_{2}\dots p_{k}
\]
thus $666 = 2\cdot 3 \cdot 3 \cdot 37$
if $ab = n$, then a and b cannot both exceed $\sqrt{n}$. Hence any composite n is divisible by a prime $p$, which does
not exceed $\sqrt{n}$
The primes in (1.2.1) are not necessarily distinct, nor arranged in any particular order. If we arrange them in increasing
order, associate sets of equal primes into single factors, and change the notation appropriately, we obtain,
\[
n = p^{a_{1}}_{1}p^{a_{2}}_{2}\dots p^{a_{k}}_{k} \quad (a_{1}>0, a_{2}>0, \dots,\quad p_{1} < p_{2} < \dots).
\]
We then say that $n$ is expressed in /standard form/
** Theorem 2
The standard form of n is unique; apart from rearrangement of factors, n can be expressed as a product of primes in one way only.
** Theorem 3: (EUCLID'S FIRST THEOREM).
If p is prime, and $p \mid ab$, then $p \mid a$ or $p \mid b$.
** Theorem 4: (EUCLID'S SECOND THEOREM).
The number of primes is infinite.
*** First Proof (Euclid's own proof)
Let $2, 3, 5, \dots, p$ be the aggregate of primes up to $p$, and let
\[
q = 2 \cdot 3 \cdot 5 \cdots p + 1 
\]
Then $q$ is not divisible by any of the numbers $2, 3, 5, \dots, p$. It is therefore either prime, or divisible by a prime between $p$ and $q$.
In either case there is a prime greater than $p$, which proves the theorem.

The theorem is *equivalent* to
\[
\pi(x) \rightarrow \infty
\]
*** Deduction
If $p$ is the n-th prime $p_{n}$, and $q$ is defined as in ??, it is plain that
\[
q < p^{n}_{n}+1
\]
for $n>1$, and so that $p_{n+1} < p^{n}_{n}+1$

This inequality enables us to assign an upper limit to the rate of increase of $p_{n}$, and a lower limit to that of $\pi(x)$.

We can, however, obtain better limits as follows. Suppose that
\[
p_{n} < 2^{2^{n}}
\]
*** Second Proof (Pólya)
**** Theorem 16: No two Fermat's numbers have a common divisor greater than 1.
Fermat's numbers are defined by
\[
F_{n} = 2^{2^{n}} + 1
\]
For suppose that $F_{n}$ and $F_{n+k}$, where $k>0$, are two Fermat numbers, and that
\[
m\mid F_{n}, \qquad m\mid F_{n+k}
\]
If $x=2^{2^{n}}$, we have
\[
\frac{F_{n+k}-2}{F_{n}}=\frac{2^{2^{n+k}}-1}{2^{2^{n}}+1}=\frac{x^{2^{k}}-1}{x+1}=x^{2^{k}-1}-x^{2^{k}-2}+\dots -1
\]
and so $F_{n}\mid F_{n+k}-2$. Hence
\[
m\mid F_{n+k}, \qquad m\mid F_{n+k}-2
\]
and therefore $m\mid 2$. Since $F_{n}$ is odd, $m=1$, which proves the theorem.
**** Second Proof depending on Fermat's numbers
It follows that each of the numbers $F_{1}, F_{2}, \dots, F_{n}$ is divisible by an odd prime number which does not divide any of the others; and therefore that there are at least $n$ odd primes not exceeding $F_{n}$. This proves Euclid's theorem.
Also
\[
p_{n+1} \leq F_{n} = 2^{2^{n}}+1 ,
\]
and it is plain that this inequality, which is a little stronger than ??, leads to a proof of Theorem 10.
*** Moduli of Integers
A *modulus* is a system $S$ of numbers such that the sum and difference of any two members of $S$ are themselves members of $S$:
i.e.,
\[
m \in S \; . \; n \in S \rightarrow (m \pm n) \in S
\]
The single number 0 forms a modulus (the /null modulus/).

It follows from the definition of S that:
\[
a \in S \Rightarrow 0=a-a \in S \; . \; 2a = a+a \in S
\]
Repeating that argument, we see that $na\in S$ for any integral $n$ (positive or negative). More generally,
\[
a \in S \; . \; b\in S \Rightarrow xa+yb \in S
\]
for any integral $x,y$.
